sudo: required
language: generic
install:
- "./go prepare-ci"
script:
- "./go build"
deploy:
  provider: releases
  api_key:
    secure: VvuajVTj1ANWpntJsRFALbVza2qmfFSVsboNMypkWNVs/0Gq3m89cDt+WI8WNnCppWyRfeTfNUCSHW15OZJ9aph+XnCiGYJdFHSZsDLzrU3tmZanPk61cy/PYWR1zM9ALvkW3GqqfFyn+EukzpflNOAV+vBdzaHUeOhI62qjilqOjDKO21nnKsh+t52JnsGBE1UywLclWDaoOhY7tFFBMjEzM6340ka8N3EC0/FQWa5tVaXTA7xMAtT661zyJv6kBwbNKHKkE9tblXZuLyp+2XMGdR/IwfGmaxO9e5d8HxUq7AObQNlgUrsIgiod1uSIECTWU3ftolVNN5DGB2Eq9MvpK0vQPtOuvCgJDr7oPRyN/3dIWKiCbSjCfbBmqsWO9cdgNMF2ZvPOOkzGlXP4qsT6a3BGTJGdSaVp566IjdUSWmc1L0ebICxI/cX8Hcg+dliDQe6+0o/+NC4E1q9wBxRsUNsOXBo1grPIuceipck/qgilPA7+GuHrsm6MxH18UE/g3oJCgoBtj0zaEM59ZFXeivP2y31tmgpmR44r5VzYdSrCugVMoTTyDzTlZ4lFsdZnAsbZdTLuX4h/qnXea8WJS6ivdhy1cOAv6KEzIysakVc1PT/1BN3Ydk4o+oOXeGroL0fTx4uJ/YN8AhXtYjUjqRXSbm0gy5i6Go5qKWc=
  file: resume-jakob-holderbaum.pdf
  skip_cleanup: true
  on:
    repo: holderbaum/resume
    branch: master
    tags: true
